### ISSUE TITLE
UnicodeEncodeError - 'charmap' codec can't encode characters in position

### ISSUE THREAD

**Issue by atkedu** [alexal1/Insomniac#127]
Hello guys i m facing this issue on 2.2.1

[Crash-2020-10-06-19-38-50.zip](https://github.com/alexal1/Insomniac/files/5337284/Crash-2020-10-06-19-38-50.zip)
[Crash-2020-10-06-19-40-29.zip](https://github.com/alexal1/Insomniac/files/5337287/Crash-2020-10-06-19-40-29.zip)
[Crash-2020-10-06-19-41-19.zip](https://github.com/alexal1/Insomniac/files/5337288/Crash-2020-10-06-19-41-19.zip)

Any help? Thank you!

**Comment by alexal1** [comment]
Strange, why logs are missing?
Could you attach full logs here?

**Comment by atkedu** [comment]
Not sure why logs are missing, it was creating a folder instead of a .zip file.

The related problem seems to be solved on 2.2.3, i will close this topic, if necessary i reopen it,

Thank you!

**Comment by 10000hzl** [comment]
Hi, this still happens (I'm on version 2.2.8). Apparently it happens when trying to unfollow a user who has non-unicode characters in the name (I'm pretty sure I also saw it happen if the non-unicode characters are in the profile bio).

![Screenshot_1](https://user-images.githubusercontent.com/29522006/96131212-3001c500-0ef9-11eb-85af-7e143a6f7ea2.png)

**Comment by arthurspa** [comment]
The logs are missing because it thrown an exception when calling dump_hierarchy().
To solve this we need to set encoding='utf-8' for the xml_dump file. In the printed logs it was using Windows CP1252 encoding, which does not contain ' \u0300'.
