### ISSUE TITLE
Activation on offline device??

### ISSUE THREAD

**Issue by GitNees** [alexal1/Insomniac#156]
This is a sad change, forced payment. 
I use a device without internet connection to run scripts on and in the past with was perfect, as the phone has wifi.

Sadly seems I wont be able to use the tool anymore. Hope a new one comes out, just as open and free as InstaPy used to be.
If someone knows one, let me know!

This seemed to become a nice alternative with instapy at heart, but seems not.

**Comment by alexal1** [comment]
Good service requires a team of developers, it cannot just appear out of nowhere. And developers want a reward for their work. You can still use free v2.8.8 script (it's still there).

And if the problem is exactly in offline mode, consider using [phone as a modem](https://www.pcworld.idg.com.au/article/552068/tethering_tutorial_how_use_your_android_smartphone_modem/).
