### ISSUE TITLE
Alternative Search

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#18]
Maybe more a request than a bug/issue.
But when you check followers of someone with lot of followers, if a bug appears or you just don't want the script runs h24..
You get that....

So maybe thinking about to take more randomzed interactions than one by one?

And by the way, 2 likes per profile is really short, in my case i constat that it needs at least 6 to 15 likes on one profile to have interest. (i know we can change that in the scritpt)
![Capture](https://user-images.githubusercontent.com/66672318/84519217-0ed26300-acd2-11ea-84b1-94e35d9669ff.JPG)

**Comment by Foncekar** [comment]
with "--likes-count" parameter you can already choose the number of like per profile, so you don't have to edit the code for that.

**Comment by GeikoHub** [comment]
@Foncekar yes i know that for the number of like per profile, that's  what i mentionned ;)
That's for always taking from the 1st follower of the "--bloggers" list each time you launch the script that cause problem.

So that's why i asked for something more randomized

**Comment by gvmturl** [comment]
> @Foncekar yes i know that for the number of like per profile, that's  what i mentionned ;)
> 
> That's for always taking from the 1st follower of the "--bloggers" list each time you launch the script that cause problem.
> 
> 
> 
> So that's why i asked for something more randomized 

@alexal1  think that it’s a good ideia for less calls-server without necessity 
Maybe start counting each user and when it sleep, scroll down till user count position?

**Comment by jonap339** [comment]
Hello, is there a way to add the parameters inside the script and just run the command "python insominac.py" in cmd? I'm starting python programming and can't find where to modify the script to add the parameter --blogger

I hope you have understood my query, the idea is to have a script for each account with their respective parameters

Thank you!

**Comment by gvmturl** [comment]
> Hello, is there a way to add the parameters inside the script and just run the command "python insominac.py" in cmd? I'm starting python programming and can't find where to modify the script to add the parameter --blogger
> 
> I hope you have understood my query, the idea is to have a script for each account with their respective parameters
> 
> Thank you!

Hello @jonap339  thanks for participating on our community and welcome to python.

Using a different file for each action you have to get lot of files for each combination of actions, while using parameters you can set how script will works in just a file!

**Comment by gvmturl** [comment]
@alexal1 also should be fine if bot could interact with people that interacts(likers on photos or/and commentators) with --bloggers

**Comment by jonap339** [comment]
I understand, It would be logical to be able to assemble everything from a single file since it first allows better statistical control, to see which combination works best for a certain time, etc. I think that if the idea is to automate instagram, I currently work with 9 different accounts and I want them to start alone with a timer, I could not do it and it is a shame. @alexal1  could this be possible? Parameterize in a file, execute it and all the parameters already have the same script? 
Thank you very much as always!

**Comment by gvmturl** [comment]
> I understand, It would be logical to be able to assemble everything from a single file since it first allows better statistical control, to see which combination works best for a certain time, etc. I think that if the idea is to automate instagram, I currently work with 9 different accounts and I want them to start alone with a timer, I could not do it and it is a shame. @alexal1  could this be possible? Parameterize in a file and run it? 
> 
> 
> 
> I think the operation should be the same as in instapy. Where in a single script, configure everything by parameters and run it.
> 
> Thank you very much as always!

Are you actually using instapy on these 9 accounts? How you handle it? Use proxies?

Thanks...

**Comment by jonap339** [comment]
No, I no longer use instapy, because it is highly detectable through the web, but yes, I used proxies! I currently work 2 accounts for each mobile device and I do not receive blockages (always under certain limits). I can work comfortably, 2 years working this way without problems. A bot that works through Android is everything I expected, since it allows higher limits to follow, stop following, likear, etc. On the web this is more limited.

**Comment by gvmturl** [comment]
> No, I no longer use instapy, because it is highly detectable through the web, but yes, I used proxies! Currently I work manually :( 2 accounts for each mobile device and I do not receive blockages (always under certain limits). I can work comfortably, 2 years working this way without problems. A bot that works through Android is everything I expected, since That allows you to add higher limits, stop following, likear, etc. On the web with instapy this is more limited.

Is not a problem using multiple accounts into the same network even 2 accounts per device?

Thank you.

**Comment by jonap339** [comment]
No, it is not a problem. Think of it this way, you're in a bar with 10 friends and all 10 are using Instagram, should they all be blocked? Of course not! I currently use an Android device to manage 2 accounts. I use very low limits, on each account I follow 65 people in the morning and 65 people at night. If you follow 70 and 70, in a couple of weeks you will receive blocks;)
At 65 and 65 a month, you'll get approximately 1,500 to 2,300 new followers.

2- I have not yet used Insomniac connected on two devices at the same time, since I am starting to use it and I am testing it. I understand that there is a function that uses something like: adb [-d | -e | -s serial_number], where you can choose by serial number, which device to use, but I'll try again later, after understanding "insomniac" well.

If you have any doubts I'm at your order

**Comment by alexal1** [comment]
@jonap339 
> I currently work with 9 different accounts and I want them to start alone with a timer, I could not do it and it is a shame. @alexal1 could this be possible? Parameterize in a file and run it?

By now you can simply create a shell script. It's an executable txt file with terminal commands. E.g.
```
adb connect <device1>
python insomniac.py <some arguments>
adb disconnect

adb connect <device2>
python insomniac.py <some arguments>
adb disconnect
```

If you want to start execution on particular time, you can use **cron** on Linux/macOS or some analog (I'm sure there is one) on Windows.

**Comment by jonap339** [comment]
Excellent! I'm excited about this, it was what I needed! I bet a lot on this project! I don't know much about python, but I do know a lot about instagram limits and locks. So what you need, I am at your disposal

**Comment by alexal1** [comment]
@gvmturl I've read carefully all your suggestions.

**Interaction with interactors**
Little by little we'll implement all features of InstaPy, but now I have to prioritize tasks and do the most important ones at first. Maybe it's better to create a separate issue with thoughts on new features?

**Input from txt files**
That's not a problem at all, can be done easily. Do you really need it? Seems that `--bloggers-random` is a more needed feature now.

**Using JSON**
Yes, I was thinking about it too. It's definitely better that multiple txt files.

**Skipping private accounts faster**
Already done, please check `v1.2.7`. In a slightly different way though.

**Telegram group**
Done, here it is: https://t.me/insomniac_chat. I'll add the link to the main page too.

**Comment by alexal1** [comment]
@GeikoHub
> And by the way, 2 likes per profile is really short, in my case i constat that it needs at least 6 to 15 likes on one profile to have interest. (i know we can change that in the scritpt)

Supported up to 12 likes in `v1.2.9`. More than 12 likes requires additional scrolling and also some way to distinguish already liked posts from not liked. So this will be done later.
