### ISSUE TITLE
targets.txt is not created

### ISSUE THREAD

**Issue by gitnodge** [alexal1/Insomniac#256]
Just playing around with scraping. Seems to work but the targets.txt file is not created. 

Is it inside the database? How do I connect it to another account?

**Comment by alexal1** [comment]
Thanks for the question @gitnodge! You've reminded me to update [the post](https://www.patreon.com/posts/43902968).

Well yes, it is inside the database. The reason is that people wanted to interact & scrape simultaneously, and SQLite databases give such possibility.

So, to use scraping you have to
1. Provide scraping instructions `--scrape @natgeo amazingtrips`
2. Specify the main account to update it's database `--scrape-for-account <your real username>`
3. Run another bot instance in the main account with `--interact-targets True`

I've updated the post and added a bit more details there. "targets.txt" can still be used, but you have to create it yourself and write there your "custom" targets. Good luck

**Comment by alexal1** [comment]
If everything's clear feel free to close the issue @gitnodge :)
