### ISSUE TITLE
Running past limits

### ISSUE THREAD

**Issue by mdlaizure** [alexal1/Insomniac#296]
I've noticed the bot will run even after the "like" limit has been reached. The bot will keep running till it has reached the "total successful interactions" limit. This causes the bot to skip targets till it can watch enough stories to count as a successful interaction. Is there a priority for the limits?
[insomniac_log-2021-03-22-17-14-09.log](https://github.com/alexal1/Insomniac/files/6196958/insomniac_log-2021-03-22-17-14-09.log)
SESSION #19 - ***
Start time: 2021-03-24 06:49:08.427528
Finish time: 2021-03-24 08:04:01.611982

This should be about a 30min run.
[***-usescrape-like-stor- copy.json.zip](https://github.com/alexal1/Insomniac/files/6196990/-usescrape-like-stor-.copy.json.zip)

**Comment by Fadude** [comment]
There are multiple types of limits in Insomniac:
* limit-per-source (for example - amount of follow actions per blogger's-followers)
* sessional-limit (limit that counts metrics in the context of the whole session)

In addition, there are sessional-limits that related to a specific action type, and there are some that related to any action (such as session-time).

The finger rule is - the bot will continue running, as log as there is an action that still can be executed by the bot. Meaning, if I've hit the follow-action limit, but I still didnt hit the like-action limit, then the bot will continue only liking.

How it works? when trying to figure out if a limit has been reached or not, the bot know if a limit is affecting a specific action type (such as follow-action-limit), or any-action-type (such as sessional-time-limit which is not related to a specific action type), and act accordingly.

I hope it helped you understand how Insomniac is working, in order to create better configs for your sessions :)
