### ISSUE TITLE
Traceback Loop

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#8]
Me again,
have a traceback that making a loop in the interacted users

The bot just like and re-like the same pics of the same profile after getting the error.
Saw that the "interacted_users.txt" doesn't update anymore when user job is done.
Screen under.

I'll test with a brand new vanilla download of the script tomorrow (UTM+1 for me)
(in the case that differents devices used creates a conflict)

![Capture](https://user-images.githubusercontent.com/66672318/84179883-eb67a800-aa86-11ea-99f2-67b46e1af9f4.JPG)

**Comment by alexal1** [comment]
Well, it seems to me that you've changed something in the script. It tries to like 6 or more posts in one profile, though you didn't even specify `--likes-count`. If you've changed something in the code, I can't help you, because I need to see code for debugging.

Please correct me and reopen the issue if I was wrong.

**Comment by GeikoHub** [comment]
yep, was the case to try you're right, i'll precise the script from now sorry ;)
